// AGENT-WRITTEN — tokens.ts
// Source: .systemix/tokens.bridge.json (generated by scripts/token-converter.ts from globals.css)
// Sync status: "new" = in codebase, not yet pushed to Figma Variables

export type SyncStatus = "synced" | "drift" | "stale" | "new";
export type TokenCollection = "color" | "status" | "radius" | "spacing" | "typography";

export type Token = {
  name: string;          // CSS custom property (--background)
  value: string;         // Light mode hex value
  darkValue?: string;    // Dark mode hex value (if applicable)
  figmaVariable: string; // Figma variable path (color/background)
  figmaCollection: string;
  syncStatus: SyncStatus;
  collection: TokenCollection;
  description?: string;
};

export type TokenRegistry = {
  tokens: Token[];
  lastSynced: string | null;
  figmaFileKey: string;
  connectionStatus: "connected" | "disconnected";
};

export const tokenRegistry: TokenRegistry = {
  lastSynced: null,
  figmaFileKey: "h1m7dfFILe1wGSfxwQ6U02",
  connectionStatus: "disconnected",
  tokens: [
    // ── Semantic — Color ─────────────────────────────────────────────────────
    { name: "--background",         value: "#ffffff",  darkValue: "#0a0a0a",  figmaVariable: "color/background",         figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--foreground",         value: "#0a0a0a",  darkValue: "#fafafa",  figmaVariable: "color/foreground",         figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--card",               value: "#ffffff",  darkValue: "#171717",  figmaVariable: "color/card",               figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--card-foreground",    value: "#0a0a0a",  darkValue: "#fafafa",  figmaVariable: "color/card-foreground",    figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--popover",            value: "#ffffff",  darkValue: "#171717",  figmaVariable: "color/popover",            figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--popover-foreground", value: "#0a0a0a",  darkValue: "#fafafa",  figmaVariable: "color/popover-foreground", figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--primary",            value: "#171717",  darkValue: "#e5e5e5",  figmaVariable: "color/primary",            figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--primary-foreground", value: "#fafafa",  darkValue: "#171717",  figmaVariable: "color/primary-foreground", figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--secondary",          value: "#f5f5f5",  darkValue: "#262626",  figmaVariable: "color/secondary",          figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--secondary-foreground", value: "#171717", darkValue: "#fafafa", figmaVariable: "color/secondary-foreground", figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--muted",              value: "#f5f5f5",  darkValue: "#262626",  figmaVariable: "color/muted",              figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--muted-foreground",   value: "#636363",  darkValue: "#8f8f8f",  figmaVariable: "color/muted-foreground",   figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--accent",             value: "#f5f5f5",  darkValue: "#262626",  figmaVariable: "color/accent",             figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--accent-foreground",  value: "#171717",  darkValue: "#fafafa",  figmaVariable: "color/accent-foreground",  figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--destructive",        value: "#e7000b",  darkValue: "#ff6467",  figmaVariable: "color/destructive",        figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--border",             value: "#e5e5e5",  darkValue: "#ffffff1a", figmaVariable: "color/border",            figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--input",              value: "#e5e5e5",  darkValue: "#ffffff26", figmaVariable: "color/input",             figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--ring",               value: "#a1a1a1",  darkValue: "#737373",  figmaVariable: "color/ring",               figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    // ── Semantic — Sidebar ───────────────────────────────────────────────────
    { name: "--sidebar",                   value: "#fafafa",  darkValue: "#121212",  figmaVariable: "color/sidebar",                   figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-foreground",        value: "#0a0a0a",  darkValue: "#fafafa",  figmaVariable: "sidebar/foreground",               figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-primary",           value: "#171717",  darkValue: "#e5e5e5",  figmaVariable: "sidebar/primary",                  figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-primary-foreground", value: "#fafafa", darkValue: "#171717",  figmaVariable: "sidebar/primary-foreground",       figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-accent",            value: "#f5f5f5",  darkValue: "#262626",  figmaVariable: "sidebar/accent",                   figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-accent-foreground", value: "#171717",  darkValue: "#fafafa",  figmaVariable: "sidebar/accent-foreground",        figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-border",            value: "#e5e5e5",  darkValue: "#ffffff1a", figmaVariable: "sidebar/border",                  figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    { name: "--sidebar-ring",              value: "#a1a1a1",  darkValue: "#737373",  figmaVariable: "sidebar/ring",                     figmaCollection: "Semantic", syncStatus: "new", collection: "color" },
    // ── Status ───────────────────────────────────────────────────────────────
    { name: "--status-synced",  value: "#00824d", darkValue: "#00c483", figmaVariable: "status/synced",  figmaCollection: "Status", syncStatus: "new", collection: "status", description: "Token in sync with Figma" },
    { name: "--status-drifted", value: "#d40c1a", darkValue: "#ff554c", figmaVariable: "status/drifted", figmaCollection: "Status", syncStatus: "new", collection: "status", description: "Mismatch between Figma and code" },
    { name: "--status-stale",   value: "#cd7a00", darkValue: "#f5a400", figmaVariable: "status/stale",   figmaCollection: "Status", syncStatus: "new", collection: "status", description: "Not synced recently" },
    { name: "--status-new",     value: "#7552db", darkValue: "#a688ff", figmaVariable: "status/new",     figmaCollection: "Status", syncStatus: "new", collection: "status", description: "In codebase, not yet in Figma" },
    // ── Spacing & Radius ─────────────────────────────────────────────────────
    { name: "--radius", value: "0.5rem", figmaVariable: "radius/base", figmaCollection: "Spacing & Radius", syncStatus: "new", collection: "radius", description: "Base border radius (8px)" },
  ],
};
